AWSTemplateFormatVersion: 2010-09-09
Resources:
  VPCTVLAPIUAT:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.150.0.0/16
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1f54486b-a47e-4fc9-be83-4781bda0798b
        
  SUBNETPRIVATETVLAPIUAT:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCTVLAPIUAT
      CidrBlock: 10.150.0.0/17
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b1cf83c7-72fc-4809-9378-a1222b4f8f65
        
  SUBNETPUBLICTVLAPIUAT:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCTVLAPIUAT
      CidrBlock: 10.150.128.0/17
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 389f0357-fc7b-40a1-ac4e-2dea7c366c81
        
  RTBLPUBLICUAT:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCTVLAPIUAT
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b180b2d1-d704-4589-88c1-f6fd27c71027
        
  RTBLPRIVATEUAT:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCTVLAPIUAT
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ac6491a5-1d6c-43a3-97c1-32758f21dc6f
        
  NATGWUAT:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: eipalloc-24956d4d
      SubnetId: !Ref SUBNETPRIVATETVLAPIUAT
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 798e1db6-d39a-4bfe-ba2b-96e28ec02629
        
  IGWUAT:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: name
          Value: UAT IGW
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 629c357f-d774-4887-a835-84a0d52974ca
        
  GATEWAYTOINTERNET:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPCTVLAPIUAT
      InternetGatewayId: !Ref IGWUAT
    Metadata:
      'AWS::CloudFormation::Designer':
        id: aa9bd772-64cb-4de1-8121-1ff70e10d522
        
  ROUTEUAT:
    Type: 'AWS::EC2::Route'
    DependsOn: GATEWAYTOINTERNET
    Properties:
      RouteTableId: !Ref RTBLPUBLICUAT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGWUAT
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 66bc047a-8848-444d-95ba-1470256f319f
        
  ROUTEPUBSUBNETASSOCIATE:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RTBLPUBLICUAT
      SubnetId: !Ref SUBNETPUBLICTVLAPIUAT
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2f17999a-2896-41e0-b699-9ca98cf45d34
        
  ROUTEPRISUBNETASSOCIATE:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RTBLPRIVATEUAT
      SubnetId: !Ref SUBNETPRIVATETVLAPIUAT
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9242cb0f-8a01-4661-bd60-728fd52b06e8
        
  ROUTEPRIVATEUAT:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RTBLPRIVATEUAT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref NATGWUAT
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 646cc8c8-a80f-4ef6-bd5d-96506acf66d5
        
Metadata:
  'AWS::CloudFormation::Designer':
    1f54486b-a47e-4fc9-be83-4781bda0798b:
      size:
        width: 1340
        height: 500
      position:
        x: 360
        'y': 120
      z: 0
      embeds:
        - 629c357f-d774-4887-a835-84a0d52974ca
        - ac6491a5-1d6c-43a3-97c1-32758f21dc6f
        - b180b2d1-d704-4589-88c1-f6fd27c71027
        - 389f0357-fc7b-40a1-ac4e-2dea7c366c81
        - b1cf83c7-72fc-4809-9378-a1222b4f8f65
    b1cf83c7-72fc-4809-9378-a1222b4f8f65:
      size:
        width: 140
        height: 140
      position:
        x: 504.165751066448
        'y': 215.67556397203646
      z: 1
      parent: 1f54486b-a47e-4fc9-be83-4781bda0798b
      embeds:
        - 798e1db6-d39a-4bfe-ba2b-96e28ec02629
    389f0357-fc7b-40a1-ac4e-2dea7c366c81:
      size:
        width: 140
        height: 140
      position:
        x: 820
        'y': 230
      z: 1
      parent: 1f54486b-a47e-4fc9-be83-4781bda0798b
      embeds: []
    b180b2d1-d704-4589-88c1-f6fd27c71027:
      size:
        width: 140
        height: 130
      position:
        x: 820
        'y': 440
      z: 1
      parent: 1f54486b-a47e-4fc9-be83-4781bda0798b
      embeds:
        - 66bc047a-8848-444d-95ba-1470256f319f
    ac6491a5-1d6c-43a3-97c1-32758f21dc6f:
      size:
        width: 140
        height: 140
      position:
        x: 502
        'y': 413
      z: 1
      parent: 1f54486b-a47e-4fc9-be83-4781bda0798b
      embeds:
        - 646cc8c8-a80f-4ef6-bd5d-96506acf66d5
    798e1db6-d39a-4bfe-ba2b-96e28ec02629:
      size:
        width: 60
        height: 60
      position:
        x: 710
        'y': 310
      z: 1
      parent: b1cf83c7-72fc-4809-9378-a1222b4f8f65
      embeds: []
      isrelatedto:
        - b1cf83c7-72fc-4809-9378-a1222b4f8f65
    629c357f-d774-4887-a835-84a0d52974ca:
      size:
        width: 60
        height: 60
      position:
        x: 1030
        'y': 430
      z: 1
      parent: 1f54486b-a47e-4fc9-be83-4781bda0798b
      embeds: []
    66bc047a-8848-444d-95ba-1470256f319f:
      size:
        width: 60
        height: 60
      position:
        x: 1028
        'y': 267
      z: 1
      parent: b180b2d1-d704-4589-88c1-f6fd27c71027
      embeds: []
      references:
        - 629c357f-d774-4887-a835-84a0d52974ca
      dependson:
        - 629c357f-d774-4887-a835-84a0d52974ca
        - aa9bd772-64cb-4de1-8121-1ff70e10d522
    2f17999a-2896-41e0-b699-9ca98cf45d34:
      source:
        id: b180b2d1-d704-4589-88c1-f6fd27c71027
      target:
        id: 389f0357-fc7b-40a1-ac4e-2dea7c366c81
      z: 1
    9242cb0f-8a01-4661-bd60-728fd52b06e8:
      source:
        id: ac6491a5-1d6c-43a3-97c1-32758f21dc6f
      target:
        id: b1cf83c7-72fc-4809-9378-a1222b4f8f65
      z: 1
    646cc8c8-a80f-4ef6-bd5d-96506acf66d5:
      size:
        width: 60
        height: 60
      position:
        x: 710
        'y': 460
      z: 1
      parent: ac6491a5-1d6c-43a3-97c1-32758f21dc6f
      embeds: []
      references:
        - 798e1db6-d39a-4bfe-ba2b-96e28ec02629
      isrelatedto:
        - 798e1db6-d39a-4bfe-ba2b-96e28ec02629
    aa9bd772-64cb-4de1-8121-1ff70e10d522:
      source:
        id: 629c357f-d774-4887-a835-84a0d52974ca
      target:
        id: 1f54486b-a47e-4fc9-be83-4781bda0798b
      z: 1
